version: '3.9'

services:

  #db:
   # container_name: db
    #image: mariadb
    #restart: always
    #environment:
     # MARIADB_ROOT_PASSWORD: example
    
    #volumes:
     # - ./web_datastore.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    
    #ports:
     # - 3306:3306
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8090:80"
