name: Deployment

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - deployment
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker compose build --pull
        working-directory: ./deployment
      - name: Deploy
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: docker compose up -d
        working-directory: ./deployment
